### ISSUE TITLE
As a creator, I want a login page so that I can save my work on an account.

### ISSUE THREAD

**Issue by m-r-q-w-e-r-t-y** [m-r-q-w-e-r-t-y/bees#11]
**Acceptance Tests:**

*Test 1*
1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2022-Spring/cse-442v/public_html/
2. Enter email 'test@gmail.com'
3. Enter password 'test'
4. Press login button
5. Verify that user is redirected to folder page

*Test 2*
1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2022-Spring/cse-442v/public_html/
2. Enter email 'test@gmail.com'
3. Enter password '1'
4. Press login button
5. Verify that user is given error alert

**Comment by MattJohnson24** [comment]
Tasks:
Create a username text field
Create a password text field
Create log in button
Verify valid login info

Acceptance tests:
(1) In a new window navigate to the evaluation site
(2) Log in using the username: test@buffalo.edu and password: testpassword
(3) Click Log In button
(4) Get redirected to main page
