### ISSUE TITLE
As a creator, I want a register page so that I can create an account.

### ISSUE THREAD

**Issue by m-r-q-w-e-r-t-y** [m-r-q-w-e-r-t-y/bees#12]
**Acceptance Tests:**

*Test 1*
1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2022-Spring/cse-442v/public_html/
2. Click the 'register here' button
3. Enter a your UB email
4. Enter 'test' in password and confirm password
5. Press submit button
6. Verify you are brought to the login page
7. Enter the random username from step 3
8. Verify you are brought to login page on successful login

*Test 2*
1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2022-Spring/cse-442v/public_html/
2. Click the 'register here' button
3. Enter your UB email in the email field
4. Enter 'test' in password and confirm password
5. Press submit button
6. Verify you are given an error alert for an already used email

**Comment by MattJohnson24** [comment]
Tasks:
(1) Create a sign up button
(2) Create a username text field
(3) Create a password text field
(4) Verify eligible username/password
(5) Give feedback to user if info works or not
(5) Confirmation button

Test 1:
(1) Click on sign up button on evaluation site
(2) Get redirected to sign up page
(3) Prompt user for username and password
(4) Upon entering information hit the confirm sign up button
(5) Redirected to main page on new account

Test 2:
(1) Click on sign up button on evaluation site
(2) Get redirected to sign up page
(3) Prompt user for username and password
(4) Upon entering invalid information hit the confirm sign up button
(5) User is prompted for new account info
