### ISSUE TITLE
As a creator, I want to reset my password so that I can change my password if I forget it.

### ISSUE THREAD

**Issue by m-r-q-w-e-r-t-y** [m-r-q-w-e-r-t-y/bees#13]
## Test 1
1. Go to localhost:3000/login
2. Click on forgot password
3. Enter the email of an already made account and click submit
4. Verify that user received email after submitting the reset password ticket
5. Enter code to reset password
6. Enter new password and confirm
7. Navigate to localhost:3000/login
8. Login with new password

**Comment by MattJohnson24** [comment]
**User Acceptance Test**
(1) Go to localhost:3000/login
(2) Click on forgot password
(3) Enter the email of an already made account
(4) Check email for reset password code
(5) Enter code to reset password
(6) Enter new password and confirm
(7) Navigate to localhost:3000/login
(8) Login with new account information

---

**Task 1**
(1) Forgot password page works

Acceptance test 1:
(1) Verify that clicking forgot password redirects to forgot password page

---

**Task 2**
(1) Email is sent to user

Acceptance test 2:
(1) Enter email of account with forgotten password
(2) Check email for code
(3) Code successfully works when entered
(4) Verify newly entered password works on login page
(5) Verify old password doesn't work on login page
