### ISSUE TITLE
As a user, I want to able to log out, so my account is safe to use on other computer.

### ISSUE THREAD

**Issue by B-o-s-s-e-s** [m-r-q-w-e-r-t-y/bees#14]
**Acceptance Tests:**

**Test 1**
1) Verify leads to login https://www-student.cse.buffalo.edu/CSE442-542/2022-Spring/cse-442v/public_html/
2) Enter "test@gmail.com" into username input.
3) Enter "test" into password input.
4) Verify clicking on the red arrow button leads to the "folder page"
7) Verify that clicking on the logout button takes you back to login page

**Comment by B-o-s-s-e-s** [comment]
In hamburger menu navigation Bar, have option button to sign out.

**Comment by MattJohnson24** [comment]
**User Acceptance Test**
(1) Go to localhost:3000/folder
(2) Click the three bar icon in the top right.
(3) Select logout
(4) Verify you are redirected to sign in page.

---

**Task 1**
(1) Verify that the icon in the top right works.

Acceptance Test 1:
(1) Verify that top right icon expands, showing the log out option.

---

**Task 2**
(1) Verify logout option exits account

Acceptance Test 2:
(1) Click logout option and verify that user is placed at the sign in page.
