### ISSUE TITLE
As a creator, I want to create a new document so that I can write a new note

### ISSUE THREAD

**Issue by m-r-q-w-e-r-t-y** [m-r-q-w-e-r-t-y/bees#7]
## Test 1
1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2022-Spring/cse-442v/public_html/
2. If you are not logged in use the following credentials **email**: `test01@gmail.com` and **password**: `test01`
3. Verify there is a **plus icon** in the folder page
4. Verify that clicking on the **plus icon** brings up a dialog to create a document with input `Document Name ...`
5. Enter "Test02" and press **create**
6. Verify that the folder page now has a "Test02" note

**Comment by mraddtab** [comment]
1. Create a react component "Create Document"  that redirects users to the editing page.
