### ISSUE TITLE
As a creator, I want to open an existing document so that I can work on previous note

### ISSUE THREAD

**Issue by m-r-q-w-e-r-t-y** [m-r-q-w-e-r-t-y/bees#8]
## Test 1
1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2022-Spring/cse-442v/public_html/
2. If you are not logged in use the following credentials **email**: `test01@gmail.com` and **password**: `test01`
3. Click on a existing document "API Call"
4. Verify that a code and comments already exist

**Comment by mraddtab** [comment]
Task 1
1. Create a drop down menu component.
2. Create a document component.
3. Create a card component.
4. Assemble components.  Card <-- document & menu. 

Acceptance test 1.
1. Navigate to localhost:3000/folder
2. Click on a hamburger menu icon.
3. A dropdown menu should appear.
4. Click on edit.
5. Get redirected to localhost:3000/edit
